@PizzaAPI2_HostAddress = http://localhost:5017


GET {{PizzaAPI2_HostAddress}}/ingrediente/
Accept: application/json

###

GET {{PizzaAPI2_HostAddress}}/ingrediente/2
Accept: application/json

###
PUT {{PizzaAPI2_HostAddress}}/ingrediente/5
Content-Type: application/json

{
    "Nome": "Salame",
    "Vegano": false
}

###
POST {{PizzaAPI2_HostAddress}}/ingrediente/
Content-Type: application/json

{
    "Nome": "TesteDelete",
    "Vegano": true
}

###

###

DELETE {{PizzaAPI2_HostAddress}}/ingrediente/7
Accept: application/json


