@PizzaAPI2_HostAddress = http://localhost:5017


###

GET {{PizzaAPI2_HostAddress}}/pizza/
Accept: application/json

###

POST {{PizzaAPI2_HostAddress}}/pizza/
Content-Type: application/json

{
    "Nome": "Pizza de queijo",
    "IngredientesIds": [1,2]
}

###

POST {{PizzaAPI2_HostAddress}}/pizza/
Content-Type: application/json

{
    "Nome": "Pizza de calabresa",
    "IngredientesIds": [1,2,4]
}
###

POST {{PizzaAPI2_HostAddress}}/pizza/
Content-Type: application/json

{
    "Nome": "Pizza Teste",
    "IngredientesIds": [1,2,3,5]
}

###

PUT {{PizzaAPI2_HostAddress}}/pizza/7
Content-Type: application/json

{
    "Nome": "Pizza Teste Editada",
    "IngredientesIds": [1,2,3]
}

###

DELETE {{PizzaAPI2_HostAddress}}/pizza/7
Accept: application/json

###